### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by benwallis** [stamat/youtube-background#13]
This error appears in console sometimes and sometimes stops the video from loading:

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin

**Comment by stamat** [comment]
Hey, hi! Can you please send me the link of the video in question?

**Comment by benwallis** [comment]
Thanks,

The video is unlisted, so I don't want to display the URL publicly.  Can I email/message you it somehow?

**Comment by stamat** [comment]
@benwallis no need for the video link on second thought, I see the "error" log on all the videos, but all of them play for me.  I'll add a feature to manually set the target origin when I have a moment.

Can you share your youtube-background init code together with the config params?

**Comment by benwallis** [comment]
`            if (document.querySelector('.video-banner')) {
                jQuery('[data-youtube]').youtube_background();
            }`

`<div class="video-banner" data-youtube="https://www.youtube.com/watch?v=XXXXXXXXXXX"></div>`

**Comment by rorych** [comment]
Is there any Update on this? I am getting the same error

**Comment by stamat** [comment]
@rorych I believe the error is gone now, this was cause I was setting the origin manually for god know why, but I removed that origin query from the iframe src, and now the error is gone.

To give a bit more context [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) is used to communicate between web frames, so because I was setting the origin YouTube API wanted to communicate directly to exchange messages with the frame, but couldn't since it wasn't the same origin.

Though the errors that you see are mainly due the youtube and not due this script. These errors don't prevent the intended functionality of this script and your code.
