### ISSUE TITLE
Failed to load resource and other issues

### ISSUE THREAD

**Issue by KoenTim** [stamat/youtube-background#15]
Hi, first of all: Thanks for offering this jQuery plugin for embedding YouTube videos as cover background. I do have some issues when i'm running this though. I hope you can look into this. 

Here are some screenshots for better understanding: https://imgur.com/a/AlqKVc8

**Comment by stamat** [comment]
@KoenTim hey bud, sorry for replying so late (after three years lol) and thanks for the screenshots. The issue is the same as #12 and #50, due not all videos having `maxresdefault.jpg` so this was changed to `hqdefault.jpg`. Regarding the cookies there was an update that changes the links of the videos to hopefully disable tracking cookies.

Everything is available in **v1.0.19**

Cheers! 🥂
