### ISSUE TITLE
Not working on mobile devices

### ISSUE THREAD

**Issue by procontentxyz** [stamat/youtube-background#17]
on mobile neither video is playing, nor mute and pause buttons are showing. 

why?

**Comment by enkr1** [comment]
Having the same problem

**Comment by mariez** [comment]
By default the property mobile is set to false. Did you tried adding data-ytbg-mobile="true" ?

**Comment by thomasgoemaere** [comment]
I'm having the same problem.

I've added the data attribute like in previous comment (data-ytbg-mobile="true") and also on the javascript call:

```
jQuery('[data-youtube]').youtube_background({
    'mobile': true,
 });
```

Video freezes on mobile device (iPhone X - Chrome & Safari).

Could you look into this please or am I doing something wrong?

Thank you!

Kind regards,
Thomas

**Comment by azaruddin** [comment]
if video is not working on mobile device so you need to add  data-ytbg-mobile="true" in  attribute  so it will work on mobile as well. 
Thanks

**Comment by partiallypro** [comment]
I'm having the same issue, it works on Android but on iOS it just shows a paused video. If you add the play button, once pressed the browser opens up a separate video area to play it. That is with data-ytbg-mobile="true" or setting it in the javascript.

**Comment by waifstorm** [comment]
I added 'mobile':true but it doesn't work

**Comment by jeremymouton** [comment]
Adding control buttons to the video breaks the mobile version. This happens on the demo too.

### Steps to reproduce:

1. Go to https://stamat.github.io/youtube-background/
2. Open DevTools
3. Toggle Device Toolbar and select a mobile device (eg, iPhone 12 Pro)
4. Reload and check the console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'appendChild')
    at YoutubeBackground.generateActionButton (jquery.youtube-background.js?v=1.0.8:475:27)
```

Looks like the controls element reference isn't found.

**Comment by stamat** [comment]
@jeremymouton hey bud thanks for letting me know - been quite busy so I didn't check this. Anyway please do check again if the issue persists. Also in future do open a PR when you have a fix and I'll publish it! 🙏 ❤️ 

To reference the initial issue - yes the mobile was disabled by default because I think back when I wrote the initial script the YouTube embed didn't play on mobile. At some point in time I enabled the mobile setting by default and all instances (YouTube, Vimeo and video) work on mobile. 🎉
