### ISSUE TITLE
hide related video when the video ends.

### ISSUE THREAD

**Issue by aasutossh** [stamat/youtube-background#18]
![image](https://user-images.githubusercontent.com/18498932/95570336-7f05b100-0a46-11eb-8493-66257b794ccc.png)

**Comment by jcackowskidiagram** [comment]
This is also a problem when pausing the video, due to a recent YouTube change.

**Comment by stamat** [comment]
@aasutossh @jcackowskidiagram hey, there is unfortunately nothing we can do here... This script now supports Vimeo and HTML 5 video - so these can be alternatives.

**Comment by jcackowskidiagram** [comment]
@stamat In my case, I needed to disable tab navigation accessibility on the YT iframe. The YT logo is keyboard accessible. Since this is a BG video, there is no need for the iframe to be accessible, so you could hardcode an attribute `tab-index="-1"` on the embed. That would solve the iframe shifting and making related videos visible.

You could also change the CSS positioning so that a YT iframe is 300% tall, and shifted up 100%. This will effectively hide the controls within the container.

**Comment by bantunesm** [comment]
other possibility, ending the video 1second before the end. @stamat already gave us data-vbg-end param.
We could automate this by getting the video duration, any thoughts ?
