### ISSUE TITLE
remove title from youtube video

### ISSUE THREAD

**Issue by vlrprbttst** [stamat/youtube-background#7]
hi!
is there a way to remove the title on the initial load of the yt video?
this example is using your library and no title appears: https://codepen.io/songyima/pen/VKbyYG?editors=1000
i can't figure out how he did it, the 
            `showinfo: 0`
is already set but it still shows the title.
can you help?

**Comment by stamat** [comment]
Yo! @vlrprbttst I'll take a look and see what's up! Thanks for reporting this!

**Comment by stamat** [comment]
@vlrprbttst hey man, I'm currently refactoring this code and I'll enable few things - css fade in animation and custom zoom of the video (meaning an offset where video is slightly larger than it's container - now it's only 50px on each side, but you'll be able to manually set it)

If you take a closer look, his iframe is: height: 300vh; width: 120vw;
That's why you don't see the title.

Also by the "book" https://developers.google.com/youtube/player_parameters
`showinfo: 0` is deprecated from September 25, 2018. and doesn't do anything. They probably want to prevent this what we are doing 😆 

Anyways, version 1.0.5 of this code will be up tomorrow!

🤘

**Comment by stamat** [comment]
Hey dude, check out the latest release v1.0.7, it includes manual offset setting and fade in CSS animation, so it should cover your issue. 🎉

**Comment by vlrprbttst** [comment]
thanks man!
